name: flixoo_flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+12

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  dio: ^5.4.3+1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  country_pickers: ^3.0.1
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  flutter_xlider: ^3.5.0
  flutter_inappwebview: ^6.1.5
  youtube_player_flutter: ^9.1.1
  flick_video_player: ^0.9.0
  video_player: ^2.9.5
  share_plus: ^11.0.0
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  # flutter_facebook_auth: ^7.1.0
  flutter_downloader: ^1.11.8
  lecle_yoyo_player: ^0.0.7
  shared_preferences: ^2.5.3
  # purchases_flutter: ^8.10.4
  google_mobile_ads: ^6.0.0
  # onesignal_flutter: ^5.3.4
  better_player_plus: ^1.0.8
  flutter_widget_from_html: ^0.15.3
  flutter_stripe: ^11.5.0
  flutter_file_downloader: ^2.1.0
  purchases_flutter: ^9.5.0
  # firebase_core: ^4.1.1
  # firebase_auth: ^6.1.0
  # cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.dev
    - .env.example
    - assets/images/
    - assets/svgs/
    - assets/svgs/profile/
    - assets/svgs/splash/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
